# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target '2016-06-01-codelab-frontend' do
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'ObjectMapper'
  pod 'Locksmith'
  pod 'AlamofireObjectMapper'
end
